### ISSUE TITLE
ArrayIndexOutOfBoundsException in TrendMicro android v5.1

### ISSUE THREAD

**Issue by wingjay** [layerhq/Atlas-Android#116]
Hey, Do you have any idea about this crash? Thx.

```
Fatal Exception: java.lang.ArrayIndexOutOfBoundsException: length=2048; regionStart=0; regionLength=-1
       at java.util.Arrays.checkOffsetAndCount(Arrays.java:1719)
       at libcore.io.IoBridge.write(IoBridge.java:491)
       at java.io.FileOutputStream.write(FileOutputStream.java:186)
       at java.util.MarsUtils.write(MarsUtils.java:33)
       at com.android.org.conscrypt.OpenSSLSocketImpl$SSLInputStream.read(OpenSSLSocketImpl.java:704)
       at lsdka.m$2.b(SourceFile:176)
       at lsdka.m$2.a(SourceFile:161)
       at lsdka.a$2.a(SourceFile:211)
       at lsdka.o.b(SourceFile:71)
       at lsdka.o.a(SourceFile:64)
       at lsdka.o.l(SourceFile:232)
       at com.lsdka.lsdka.lsdka.lsdkb.m$a.a(SourceFile:129)
       at com.lsdka.lsdka.lsdka.lsdkb.n$b.e(SourceFile:611)
       at com.lsdka.lsdka.lsdka.d.run(SourceFile:33)
       at java.lang.Thread.run(Thread.java:818)
```

**Comment by sokarcreative** [comment]
Same problem with android v5.1 when I'm using BitmapFactory.decodeStream on an inputStream with regionLength = -1.

**Comment by sriamar** [comment]
Hello,

I am not sure if you have resolved this issue. The callstack shows issues with Layer SDK.  If you are still having issues, please collect logs and contact Layer support using the instructions provided here.

https://docs.layer.com/sdk/android/support

Thanks
Amar
