### ISSUE TITLE
Crash while sending images( seleted from google photos) from chat

### ISSUE THREAD

**Issue by rekhaagarwal** [layerhq/Atlas-Android#126]
Steps:
When I click on the 'Gallery' option in attachment menu, I get two choices in my android device to select a photo from. One from Gallery app and Another from Photos app by Google. If I select Gallery and select any photo, it works fine. But if I choose Photos( uri should be something like: content://com.google.android.apps.photos.contentprovider/0/1/mediakey%) and select any photo from there, the app crashes with the following error message.

`Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'char[] java.lang.String.toCharArray()' on a null object reference
	at java.io.File.fixSlashes(File.java:183)
	at java.io.File.<init>(File.java:130)
	at com.layer.atlas.messagetypes.threepartimage.ThreePartImageUtils.newThreePartImageMessage(ThreePartImageUtils.java:56)
	at com.layer.atlas.messagetypes.threepartimage.GallerySender.onActivityResult(GallerySender.java:86)
	at com.involvio.src.ui.views.chat.CustomAtlasMessageComposer.onActivityResult(CustomAtlasMessageComposer.java:229)
	at com.involvio.src.activities.chat.ChatMessagesActivity.onActivityResult(ChatMessagesActivity.java:251)
	at android.app.Activity.dispatchActivityResult(Activity.java:6456)
	at android.app.ActivityThread.deliverResults(ActivityThread.java:3695)`

Similar issue: https://github.com/layerhq/Atlas-Android/issues/95

**Comment by thecombatwombat** [comment]
@rekhaagarwal sorry it took us some time to get to this!
#143 has been created to address this, so it should ship with the next version of Atlas

**Comment by sriamar** [comment]
The issue #143 is done. So, closing this.
