### ISSUE TITLE
ArrayIndexOutOfBoundsException in AtlasMessagesList

### ISSUE THREAD

**Issue by rockerhieu** [layerhq/Atlas-Android#14]
```
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.layer.atlas.messenger/com.layer.atlas.messenger.AtlasMessagesScreen}: java.lang.ArrayIndexOutOfBoundsException: length=0; index=-1
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2338)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2388)
            at android.app.ActivityThread.access$900(ActivityThread.java:148)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1319)
            at android.os.Handler.dispatchMessage(Handler.java:99)
            at android.os.Looper.loop(Looper.java:137)
            at android.app.ActivityThread.main(ActivityThread.java:5457)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:525)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:879)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:695)
            at dalvik.system.NativeStart.main(Native Method)
     Caused by: java.lang.ArrayIndexOutOfBoundsException: length=0; index=-1
            at java.util.ArrayList.get(ArrayList.java:310)
            at com.layer.atlas.AtlasMessagesList.updateValues(AtlasMessagesList.java:437)
            at com.layer.atlas.AtlasMessagesList.setConversation(AtlasMessagesList.java:568)
            at com.layer.atlas.messenger.AtlasMessagesScreen.onCreate(AtlasMessagesScreen.java:182)
            at android.app.Activity.performCreate(Activity.java:5234)
            at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2302)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2388)
            at android.app.ActivityThread.access$900(ActivityThread.java:148)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1319)
            at android.os.Handler.dispatchMessage(Handler.java:99)
            at android.os.Looper.loop(Looper.java:137)
            at android.app.ActivityThread.main(ActivityThread.java:5457)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:525)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:879)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:695)
            at dalvik.system.NativeStart.main(Native Method)
```

**Comment by mojodojo-in** [comment]
I'm facing the same issue. In my case, I'm trying to use the Platform API with a sender.name instead of sender.user_id. The MessageList seems not to support messages without sender.user_id.

**Comment by sjones94549** [comment]
Sorry about that -- just merged a fix: https://github.com/layerhq/Atlas-Android/pull/17
