### ISSUE TITLE
DISTINCT_CONVERSATION_EXISTS when creating a new conversation with layer-atlas-messenger

### ISSUE THREAD

**Issue by rockerhieu** [layerhq/Atlas-Android#15]
```
07-21 10:38:25.432  10181-10181/com.layer.atlas.messenger E/AndroidRuntime﹕ FATAL EXCEPTION: main
    com.layer.sdk.exceptions.LayerConversationException: DISTINCT_CONVERSATION_EXISTS (1029) - A distinct conversation with same set of participants exists already : ConversationImpl [  id: layer:///conversations/ef902080-c424-4042-8fd6-c7b0f34ca167, mParticipants: [0: 0 : participant [  mMemberId: 0, mDatabaseId: 13, mConversationDatabaseId: 3, mStreamMemberDatabaseId: 14], 1: 1 : participant [  mMemberId: 1, mDatabaseId: 14, mConversationDatabaseId: 3, mStreamMemberDatabaseId: 13]], mStreamDatabaseId: 3, mStreamId: ef902080-c424-4042-8fd6-c7b0f34ca167, mCreatedAt: Thu Jan 01 07:00:02 GMT+07:00 1970, mDatabaseId: 3, mDistinct: true]
            at com.layer.sdk.internal.LayerClientImpl.newConversation(LayerClientImpl.java:1485)
            at com.layer.sdk.LayerClient.newConversation(LayerClient.java:272)
            at com.layer.atlas.messenger.AtlasMessagesScreen.ensureConversationReady(AtlasMessagesScreen.java:242)
            at com.layer.atlas.messenger.AtlasMessagesScreen.access$000(AtlasMessagesScreen.java:74)
            at com.layer.atlas.messenger.AtlasMessagesScreen$1.beforeSend(AtlasMessagesScreen.java:125)
            at com.layer.atlas.AtlasMessageComposer$3.onClick(AtlasMessageComposer.java:187)
            at android.view.View.performClick(View.java:4240)
            at android.view.View$PerformClick.run(View.java:17752)
            at android.os.Handler.handleCallback(Handler.java:730)
            at android.os.Handler.dispatchMessage(Handler.java:92)
            at android.os.Looper.loop(Looper.java:137)
            at android.app.ActivityThread.main(ActivityThread.java:5457)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:525)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:879)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:695)
            at dalvik.system.NativeStart.main(Native Method)
```

**Comment by sjones94549** [comment]
When we introduced "distinct" conversations in 0.14.0, we added this Exception to differentiate new- from existing- conversations like this:
 
```java
Conversation conversation;
try {
    // New distinct conversation
    conversation = App.getLayerClient().newConversation(participants);
} catch (LayerConversationException e) {
    // Reuse existing distinct conversation
    conversation = e.getConversation();
}
```
