### ISSUE TITLE
Error while authenticating Android 7.1.1

### ISSUE THREAD

**Issue by kenzo23312** [layerhq/Atlas-Android#162]
Got below error while trying to authenticate user on Android 7.1.1 Nexus 5X

`LayerSDK: k : TransportException
                                                             java.net.SocketException: Socket is closed
                                                                 at com.android.org.conscrypt.OpenSSLSocketImpl.checkOpen(OpenSSLSocketImpl.java:270)
                                                                 at com.android.org.conscrypt.OpenSSLSocketImpl.-wrap0(OpenSSLSocketImpl.java)
                                                                 at com.android.org.conscrypt.OpenSSLSocketImpl$SSLOutputStream.write(OpenSSLSocketImpl.java:809)
                                                                 at lsdka.m$1.b(Okio.java:98)
                                                                 at lsdka.m$1.a_(Okio.java:83)
                                                                 at lsdka.a$1.a_(AsyncTimeout.java:155)
                                                                 at lsdka.n.flush(RealBufferedSink.java:221)
                                                                 at com.lsdka.lsdka.lsdka.lsdkb.m$b.a(Spdy3.java:339)
                                                                 at com.lsdka.lsdka.lsdka.lsdkb.n.a(SpdyConnection.java:283)
                                                                 at com.lsdka.lsdka.lsdka.lsdkb.n.a(SpdyConnection.java:259)
                                                                 at com.lsdka.lsdka.lsdka.lsdka.r.a(SpdyTransport.java:98)
                                                                 at com.lsdka.lsdka.lsdka.lsdka.g$a.a(HttpEngine.java:920)
                                                                 at com.lsdka.lsdka.lsdka.lsdka.g.l(HttpEngine.java:790)
                                                                 at com.lsdka.lsdka.e.a(Call.java:274)
                                                                 at com.lsdka.lsdka.e$a.a(Call.java:230)
                                                                 at com.lsdka.lsdka.e.a(Call.java:201)
                                                                 at com.lsdka.lsdka.e.a(Call.java:81)
                                                                 at com.layer.transport.lsdkb.b.a(LayerHttp.java:289)
                                                                 at com.layer.transport.lsdkb.b.a(LayerHttp.java:280)
                                                                 at com.layer.transport.lsdkb.b.a(LayerHttp.java:178)
                                                                 at com.layer.transport.lsdkb.b.a(LayerHttp.java:173)
                                                                 at com.layer.transport.lsdkc.k$23.a(Transport.java:505)
                                                                 at com.layer.transport.lsdkc.k$f.a(Transport.java:378)
                                                                 at com.layer.transport.lsdkc.k.a(Transport.java:502)
                                                                 at com.layer.sdk.lsdka.lsdki.lsdkc.lsdka.g.a(GetStreamsTask.java:203)
                                                                 at com.layer.sdk.lsdka.lsdki.lsdkc.lsdka.g.a(GetStreamsTask.java:84)
                                                                 at com.layer.sdk.lsdka.lsdki.lsdkc.lsdka.g.a(GetStreamsTask.java:38)
                                                                 at com.layer.lsdka.lsdkc.d.run(Task.java:172)
                                                                 at com.layer.lsdka.lsdkc.a.run(DependentTask.java:171)
                                                                 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
                                                                 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
                                                                 at java.lang.Thread.run(Thread.java:761)
03-22 13:53:24.192 4288-4498/io.myinvite.android E/LayerSDK: g : Exception in fetchStreams
                                                             com.layer.transport.lsdkc.m: Socket is closed
                                                                 at com.layer.transport.lsdkc.k$f.a(Transport.java:406)
                                                                 at com.layer.transport.lsdkc.k.a(Transport.java:502)
                                                                 at com.layer.sdk.lsdka.lsdki.lsdkc.lsdka.g.a(GetStreamsTask.java:203)
                                                                 at com.layer.sdk.lsdka.lsdki.lsdkc.lsdka.g.a(GetStreamsTask.java:84)
                                                                 at com.layer.sdk.lsdka.lsdki.lsdkc.lsdka.g.a(GetStreamsTask.java:38)
                                                                 at com.layer.lsdka.lsdkc.d.run(Task.java:172)
                                                                 at com.layer.lsdka.lsdkc.a.run(DependentTask.java:171)
                                                                 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
                                                                 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
                                                                 at java.lang.Thread.run(Thread.java:761)
                                                              Caused by: java.net.SocketException: Socket is closed
                                                                 at com.android.org.conscrypt.OpenSSLSocketImpl.checkOpen(OpenSSLSocketImpl.java:270)
                                                                 at com.android.org.conscrypt.OpenSSLSocketImpl.-wrap0(OpenSSLSocketImpl.java)
                                                                 at com.android.org.conscrypt.OpenSSLSocketImpl$SSLOutputStream.write(OpenSSLSocketImpl.java:809)
                                                                 at lsdka.m$1.b(Okio.java:98)
                                                                 at lsdka.m$1.a_(Okio.java:83)
                                                                 at lsdka.a$1.a_(AsyncTimeout.java:155)
                                                                 at lsdka.n.flush(RealBufferedSink.java:221)
                                                                 at com.lsdka.lsdka.lsdka.lsdkb.m$b.a(Spdy3.java:339)
                                                                 at com.lsdka.lsdka.lsdka.lsdkb.n.a(SpdyConnection.java:283)
                                                                 at com.lsdka.lsdka.lsdka.lsdkb.n.a(SpdyConnection.java:259)
                                                                 at com.lsdka.lsdka.lsdka.lsdka.r.a(SpdyTransport.java:98)
                                                                 at com.lsdka.lsdka.lsdka.lsdka.g$a.a(HttpEngine.java:920)
                                                                 at com.lsdka.lsdka.lsdka.lsdka.g.l(HttpEngine.java:790)
                                                                 at com.lsdka.lsdka.e.a(Call.java:274)
                                                                 at com.lsdka.lsdka.e$a.a(Call.java:230)
                                                                 at com.lsdka.lsdka.e.a(Call.java:201)
                                                                 at com.lsdka.lsdka.e.a(Call.java:81)
                                                                 at com.layer.transport.lsdkb.b.a(LayerHttp.java:289)
                                                                 at com.layer.transport.lsdkb.b.a(LayerHttp.java:280)
                                                                 at com.layer.transport.lsdkb.b.a(LayerHttp.java:178)
                                                                 at com.layer.transport.lsdkb.b.a(LayerHttp.java:173)
                                                                 at com.layer.transport.lsdkc.k$23.a(Transport.java:505)
                                                                 at com.layer.transport.lsdkc.k$f.a(Transport.java:378)
                                                                 at com.layer.transport.lsdkc.k.a(Transport.java:502) 
                                                                 at com.layer.sdk.lsdka.lsdki.lsdkc.lsdka.g.a(GetStreamsTask.java:203) 
                                                                 at com.layer.sdk.lsdka.lsdki.lsdkc.lsdka.g.a(GetStreamsTask.java:84) 
                                                                 at com.layer.sdk.lsdka.lsdki.lsdkc.lsdka.g.a(GetStreamsTask.java:38) 
                                                                 at com.layer.lsdka.lsdkc.d.run(Task.java:172) 
                                                                 at com.layer.lsdka.lsdkc.a.run(DependentTask.java:171) 
                                                                 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133) 
                                                                 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607) 
                                                                 at java.lang.Thread.run(Thread.java:761) 
03-22 13:53:24.193 4288-4498/io.myinvite.android E/LayerSDK: c : Error in TaskMaster
                                                             com.layer.lsdka.lsdkc.e: Socket is closed
                                                                 at com.layer.sdk.lsdka.lsdki.lsdkc.lsdka.g.a(GetStreamsTask.java:289)
                                                                 at com.layer.sdk.lsdka.lsdki.lsdkc.lsdka.g.a(GetStreamsTask.java:84)
                                                                 at com.layer.sdk.lsdka.lsdki.lsdkc.lsdka.g.a(GetStreamsTask.java:38)
                                                                 at com.layer.lsdka.lsdkc.d.run(Task.java:172)
                                                                 at com.layer.lsdka.lsdkc.a.run(DependentTask.java:171)
                                                                 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
                                                                 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
                                                                 at java.lang.Thread.run(Thread.java:761)
                                                              Caused by: com.layer.transport.lsdkc.m: Socket is closed
                                                                 at com.layer.transport.lsdkc.k$f.a(Transport.java:406)
                                                                 at com.layer.transport.lsdkc.k.a(Transport.java:502)
                                                                 at com.layer.sdk.lsdka.lsdki.lsdkc.lsdka.g.a(GetStreamsTask.java:203)
                                                                 at com.layer.sdk.lsdka.lsdki.lsdkc.lsdka.g.a(GetStreamsTask.java:84) 
                                                                 at com.layer.sdk.lsdka.lsdki.lsdkc.lsdka.g.a(GetStreamsTask.java:38) 
                                                                 at com.layer.lsdka.lsdkc.d.run(Task.java:172) 
                                                                 at com.layer.lsdka.lsdkc.a.run(DependentTask.java:171) 
                                                                 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133) 
                                                                 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607) 
                                                                 at java.lang.Thread.run(Thread.java:761) 
                                                              Caused by: java.net.SocketException: Socket is closed
                                                                 at com.android.org.conscrypt.OpenSSLSocketImpl.checkOpen(OpenSSLSocketImpl.java:270)
                                                                 at com.android.org.conscrypt.OpenSSLSocketImpl.-wrap0(OpenSSLSocketImpl.java)
                                                                 at com.android.org.conscrypt.OpenSSLSocketImpl$SSLOutputStream.write(OpenSSLSocketImpl.java:809)
                                                                 at lsdka.m$1.b(Okio.java:98)
                                                                 at lsdka.m$1.a_(Okio.java:83)
                                                                 at lsdka.a$1.a_(AsyncTimeout.java:155)
                                                                 at lsdka.n.flush(RealBufferedSink.java:221)
                                                                 at com.lsdka.lsdka.lsdka.lsdkb.m$b.a(Spdy3.java:339)
                                                                 at com.lsdka.lsdka.lsdka.lsdkb.n.a(SpdyConnection.java:283)
                                                                 at com.lsdka.lsdka.lsdka.lsdkb.n.a(SpdyConnection.java:259)
                                                                 at com.lsdka.lsdka.lsdka.lsdka.r.a(SpdyTransport.java:98)
                                                                 at com.lsdka.lsdka.lsdka.lsdka.g$a.a(HttpEngine.java:920)
                                                                 at com.lsdka.lsdka.lsdka.lsdka.g.l(HttpEngine.java:790)
                                                                 at com.lsdka.lsdka.e.a(Call.java:274)
                                                                 at com.lsdka.lsdka.e$a.a(Call.java:230)
                                                                 at com.lsdka.lsdka.e.a(Call.java:201)
                                                                 at com.lsdka.lsdka.e.a(Call.java:81)
                                                                 at com.layer.transport.lsdkb.b.a(LayerHttp.java:289)
                                                                 at com.layer.transport.lsdkb.b.a(LayerHttp.java:280)
                                                                 at com.layer.transport.lsdkb.b.a(LayerHttp.java:178)
                                                                 at com.layer.transport.lsdkb.b.a(LayerHttp.java:173)
                                                                 at com.layer.transport.lsdkc.k$23.a(Transport.java:505)
                                                                 at com.layer.transport.lsdkc.k$f.a(Transport.java:378)
                                                                 at com.layer.transport.lsdkc.k.a(Transport.java:502) 
                                                                 at com.layer.sdk.lsdka.lsdki.lsdkc.lsdka.g.a(GetStreamsTask.java:203) 
                                                                 at com.layer.sdk.lsdka.lsdki.lsdkc.lsdka.g.a(GetStreamsTask.java:84) 
                                                                 at com.layer.sdk.lsdka.lsdki.lsdkc.lsdka.g.a(GetStreamsTask.java:38) 
                                                                 at com.layer.lsdka.lsdkc.d.run(Task.java:172) 
                                                                 at com.layer.lsdka.lsdkc.a.run(DependentTask.java:171) 
                                                                 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133) 
                                                                 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607) 
                                                                 at java.lang.Thread.run(Thread.java:761) 
03-22 13:53:24.643 4288-4493/io.myinvite.android E/LayerSDK: a : Exception during sync
                                                             com.layer.sdk.exceptions.LayerException: UNKNOWN (1000) - Socket is closed
                                                                 at com.layer.sdk.lsdka.lsdki.a$d.a(SyncRecon.java:591)
                                                                 at com.layer.sdk.lsdka.lsdki.a$d.run(SyncRecon.java:767)
                                                                 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
                                                                 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
                                                                 at java.lang.Thread.run(Thread.java:761)
                                                              Caused by: com.layer.transport.lsdkc.m: Socket is closed
                                                                 at com.layer.transport.lsdkc.k$f.a(Transport.java:406)
                                                                 at com.layer.transport.lsdkc.k.a(Transport.java:502)
                                                                 at com.layer.sdk.lsdka.lsdki.lsdkc.lsdka.g.a(GetStreamsTask.java:203)
                                                                 at com.layer.sdk.lsdka.lsdki.lsdkc.lsdka.g.a(GetStreamsTask.java:84)
                                                                 at com.layer.sdk.lsdka.lsdki.lsdkc.lsdka.g.a(GetStreamsTask.java:38)
                                                                 at com.layer.lsdka.lsdkc.d.run(Task.java:172)
                                                                 at com.layer.lsdka.lsdkc.a.run(DependentTask.java:171)
                                                                 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133) 
                                                                 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607) 
                                                                 at java.lang.Thread.run(Thread.java:761) 
                                                              Caused by: java.net.SocketException: Socket is closed
                                                                 at com.android.org.conscrypt.OpenSSLSocketImpl.checkOpen(OpenSSLSocketImpl.java:270)
                                                                 at com.android.org.conscrypt.OpenSSLSocketImpl.-wrap0(OpenSSLSocketImpl.java)
                                                                 at com.android.org.conscrypt.OpenSSLSocketImpl$SSLOutputStream.write(OpenSSLSocketImpl.java:809)
                                                                 at lsdka.m$1.b(Okio.java:98)
                                                                 at lsdka.m$1.a_(Okio.java:83)
                                                                 at lsdka.a$1.a_(AsyncTimeout.java:155)
                                                                 at lsdka.n.flush(RealBufferedSink.java:221)
                                                                 at com.lsdka.lsdka.lsdka.lsdkb.m$b.a(Spdy3.java:339)
                                                                 at com.lsdka.lsdka.lsdka.lsdkb.n.a(SpdyConnection.java:283)
                                                                 at com.lsdka.lsdka.lsdka.lsdkb.n.a(SpdyConnection.java:259)
                                                                 at com.lsdka.lsdka.lsdka.lsdka.r.a(SpdyTransport.java:98)
                                                                 at com.lsdka.lsdka.lsdka.lsdka.g$a.a(HttpEngine.java:920)
                                                                 at com.lsdka.lsdka.lsdka.lsdka.g.l(HttpEngine.java:790)
                                                                 at com.lsdka.lsdka.e.a(Call.java:274)
                                                                 at com.lsdka.lsdka.e$a.a(Call.java:230)
                                                                 at com.lsdka.lsdka.e.a(Call.java:201)
                                                                 at com.lsdka.lsdka.e.a(Call.java:81)
                                                                 at com.layer.transport.lsdkb.b.a(LayerHttp.java:289)
                                                                 at com.layer.transport.lsdkb.b.a(LayerHttp.java:280)
                                                                 at com.layer.transport.lsdkb.b.a(LayerHttp.java:178)
                                                                 at com.layer.transport.lsdkb.b.a(LayerHttp.java:173)
                                                                 at com.layer.transport.lsdkc.k$23.a(Transport.java:505)
                                                                 at com.layer.transport.lsdkc.k$f.a(Transport.java:378)
                                                                 at com.layer.transport.lsdkc.k.a(Transport.java:502) 
                                                                 at com.layer.sdk.lsdka.lsdki.lsdkc.lsdka.g.a(GetStreamsTask.java:203) 
                                                                 at com.layer.sdk.lsdka.lsdki.lsdkc.lsdka.g.a(GetStreamsTask.java:84) 
                                                                 at com.layer.sdk.lsdka.lsdki.lsdkc.lsdka.g.a(GetStreamsTask.java:38) 
                                                                 at com.layer.lsdka.lsdkc.d.run(Task.java:172) 
                                                                 at com.layer.lsdka.lsdkc.a.run(DependentTask.java:171) 
                                                                 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133) 
                                                                 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607) 
                                                                 at java.lang.Thread.run(Thread.java:761) `

**Comment by csbrandt** [comment]
@kenzo23312 

If you could please reproduce this issue and capture the logs using instructions at https://docs.layer.com/sdk/android/support, so that we may assist with troubleshooting your issue.

You will receive an email reply confirming that we’ve received your ticket. This will contain a Ticket ID. Please use that ID as reference in any further communication regarding this issue.

**Comment by andela-wakinsanmi** [comment]
Hello @kenzo23312 

Thanks for reaching out. Can you please follow the steps in https://docs.layer.com/sdk/android/support as pointed out by @csbrandt .

The log will give more insight into what's going on. This is an SDK issue and we track it througha different support system and not through github repository.

Thanks
