### ISSUE TITLE
Issue with GCM

### ISSUE THREAD

**Issue by IHNEL** [layerhq/Atlas-Android#164]
I was using Layer 0.2.11 for 2 years ago. There are some random crashes so I decide to upgrade to latest version 0.4.5.
Now I have new issue that can't setup receiver with GCM and can't start the app. Here is the crash log, please help

```
03-23 21:08:43.872 30219-30219/com.unibly.unibly_android.stg E/AndroidRuntime: FATAL EXCEPTION: main
                                                                               Process: com.unibly.unibly_android.stg, PID: 30219
                                                                               java.lang.RuntimeException: Unable to instantiate receiver com.layer.sdk.services.GcmBroadcastReceiver: java.lang.ClassNotFoundException: Didn't find class "com.layer.sdk.services.GcmBroadcastReceiver" on path: DexPathList[[zip file "/data/app/com.unibly.unibly_android.stg-2/base.apk"],nativeLibraryDirectories=[/data/app/com.unibly.unibly_android.stg-2/lib/x86, /vendor/lib, /system/lib]]
                                                                                   at android.app.ActivityThread.handleReceiver(ActivityThread.java:2706)
                                                                                   at android.app.ActivityThread.-wrap14(ActivityThread.java)
                                                                                   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1421)
                                                                                   at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                   at android.os.Looper.loop(Looper.java:148)
                                                                                   at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                                   at java.lang.reflect.Method.invoke(Native Method)
                                                                                   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
                                                                                Caused by: java.lang.ClassNotFoundException: Didn't find class "com.layer.sdk.services.GcmBroadcastReceiver" on path: DexPathList[[zip file "/data/app/com.unibly.unibly_android.stg-2/base.apk"],nativeLibraryDirectories=[/data/app/com.unibly.unibly_android.stg-2/lib/x86, /vendor/lib, /system/lib]]
                                                                                   at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                                                                                   at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
                                                                                   at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
                                                                                   at android.app.ActivityThread.handleReceiver(ActivityThread.java:2701)
                                                                                   at android.app.ActivityThread.-wrap14(ActivityThread.java) 
                                                                                   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1421) 
                                                                                   at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                   at android.os.Looper.loop(Looper.java:148) 
                                                                                   at android.app.ActivityThread.main(ActivityThread.java:5417) 
                                                                                   at java.lang.reflect.Method.invoke(Native Method) 
                                                                                   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
                                                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 
                                                                               	Suppressed: java.lang.ClassNotFoundException: com.layer.sdk.services.GcmBroadcastReceiver
                                                                                   at java.lang.Class.classForName(Native Method)
                                                                                   at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
                                                                                   at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
                                                                                   at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
                                                                                   		... 10 more
                                                                                Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack trace available
```

**Comment by csbrandt** [comment]
@IHNEL 
If you could please reproduce this issue and capture the logs using instructions at https://docs.layer.com/sdk/android/support, so that we may assist with troubleshooting your issue.

You will receive an email reply confirming that we’ve received your ticket. This will contain a Ticket ID. Please use that ID as reference in any further communication regarding this issue.

**Comment by IHNEL** [comment]
Thanks for quick reply, but how can I send the log while the app crash? The crash log above is what I have.

**Comment by IHNEL** [comment]
I setup the Layer SDK via gradle, and register receiver in my Manifest like this:
```
<receiver
            android:name="com.layer.sdk.services.GcmBroadcastReceiver"
            android:permission="com.google.android.c2dm.permission.SEND">
            <intent-filter android:priority="470">
                <action android:name="com.google.android.c2dm.intent.RECEIVE"/>
                <action android:name="com.google.android.c2dm.intent.REGISTRATION"/>
                <action android:name="com.google.android.c2dm.intent.REGISTER"/>

                <category android:name="${applicationId}"/>
            </intent-filter>
        </receiver>
        <!--Service: Layer SDK GCM handling -->
        <service android:name="com.layer.sdk.services.GcmIntentService"/>
```

What I saw is the `com.layer.sdk.services.GcmBroadcastReceiver` shown as Red color, mean it can't be found in the layer SDK. I also try to lookup for that source file but found nothing.

I wonder why you closed the issue while didn't help to resolve it?

**Comment by IHNEL** [comment]
Found the root cause:

> The GcmBroadcastReceiver and GcmIntentService have been removed. Remove the com.layer.sdk.services.GcmBroadcastReceiver and com.layer.sdk.services.GcmIntentService components in your AndroidManifest.xml.

Add the following to your AndroidManifest.xml:
```

<service
    android:name="com.layer.sdk.services.LayerFcmService"
    android:exported="false">
    <intent-filter>
        <action android:name="com.google.firebase.MESSAGING_EVENT" />
    </intent-filter>
</service>
<service
    android:name="com.layer.sdk.services.LayerFcmInstanceIdService"
    android:exported="false">
    <intent-filter>
        <action android:name="com.google.firebase.INSTANCE_ID_EVENT"/>
    </intent-filter>
</service>
```

**Comment by rockerhieu** [comment]
I got this issue also, is there a solution for this?

**Comment by IHNEL** [comment]
@rockerhieu see my above update, https://github.com/layerhq/Atlas-Android/issues/164#issuecomment-288955715
