### ISSUE TITLE
 Session with different IDs already active.

### ISSUE THREAD

**Issue by IHNEL** [layerhq/Atlas-Android#165]
I'm using Layer 0.2.11. I have been use this version on my app for 2 years
For authentication, I ask user signup first, then sign in. after User sign In success awhile ( not immediately) Layer throws an exception like this:

```
03-23 22:56:48.659 6708-8401/com.unibly.unibly_android.stg E/LayerSDK: a : Trying to authenticate a new user when a different user ( 52793fa2-0fe1-11e7-add9-e4f7be0615a5 ) is already authenticated. Existing user: jNhb9DgNPS
03-23 22:56:48.659 6708-8401/com.unibly.unibly_android.stg E/AndroidRuntime: FATAL EXCEPTION: pool-15-thread-1
                                                                             Process: com.unibly.unibly_android.stg, PID: 6708
                                                                             java.lang.IllegalStateException: Session with different IDs already active. Currently active id: jNhb9DgNPS
                                                                                 at com.layer.sdk.lsdka.a.a(LayerClientImpl.java:935)
                                                                                 at com.layer.sdk.lsdka.a.a(LayerClientImpl.java:1041)
                                                                                 at com.layer.sdk.lsdka.lsdkk.lsdka.a.a(AuthManager.java:645)
                                                                                 at com.layer.sdk.lsdka.lsdkk.lsdka.a$1.b(AuthManager.java:476)
                                                                                 at com.layer.lsdka.lsdkc.c.run(RetryableTask.java:193)
                                                                                 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                                 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                                 at java.lang.Thread.run(Thread.java:818)
```

Any solution to fix?

**Comment by csbrandt** [comment]
@IHNEL 
If you could please reproduce this issue and capture the logs using instructions at https://docs.layer.com/sdk/android/support, so that we may assist with troubleshooting your issue.

You will receive an email reply confirming that we’ve received your ticket. This will contain a Ticket ID. Please use that ID as reference in any further communication regarding this issue.

**Comment by derekcsm** [comment]
I'm running into the same issue, it would really help if the resolution to this was made public - and not potentially resolved within a support ticket.

**Comment by Eclair** [comment]
Same here, It would be supper helpful if you at least post some explanation on why this issue is happening and on what step. Does it happen when we start authentication? or AnswerAuthenticationChallenge?

**Comment by riteshwarke** [comment]
I'm running into the same issue, it would really help if the resolution to this was made public - and not potentially resolved within a support ticket.   AGREED
