### ISSUE TITLE
NPE: SinglePartImageCellFactory starts AtlasImagePopupActivity with null fullId

### ISSUE THREAD

**Issue by explodes** [layerhq/Atlas-Android#172]
If the `fullId` extra is not set in `AtlasImagePopupActivity` then the Activity will fail to start because `ImageSource.uri(Uri)` will throw an NPE if the uri is null.

This trace was taken from logging:
```java
Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.foo.app.android/com.layer.atlas.util.imagepopup.AtlasImagePopupActivity}: java.lang.NullPointerException: Uri must not be null
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2419)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2479)
       at android.app.ActivityThread.-wrap11(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1347)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:5420)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
Caused by java.lang.NullPointerException: Uri must not be null
       at com.davemorrissey.labs.subscaleview.ImageSource.uri(ImageSource.java:111)
       at com.layer.atlas.util.imagepopup.AtlasImagePopupActivity.onCreate(AtlasImagePopupActivity.java:83)
       at android.app.Activity.performCreate(Activity.java:6280)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2372)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2479)
       at android.app.ActivityThread.-wrap11(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1347)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:5420)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

Unfortunately, I don't have any steps to reproduce this error consistently.

Peeking around the code, it is clear that will be caused when any of a Message's parts has no id for some reason:

```java
    @Override
    public PartId parseContent(LayerClient layerClient, Message message) {
        for (MessagePart part : message.getMessageParts()) {
            if (part.getMimeType().startsWith("image/")) return new PartId(part.getId());
        }
        return null;
    }
```

A simple fix here could be a null-check on `part.getId()`

**Comment by andela-wakinsanmi** [comment]
Hello @explodes 

I want to find out if the steps in the PR referenced solved your issue before I close it.

**Comment by explodes** [comment]
It fixes the crash, but not the issue. Closing!

**Comment by andela-wakinsanmi** [comment]
Can you please enable log in the app by following https://docs.layer.com/sdk/android/support This will help us have a better picture of exactly what's going on.

Thanks
