### ISSUE TITLE
Crash on CameraSender

### ISSUE THREAD

**Issue by rajohns08** [layerhq/Atlas-Android#208]
Nexus 5 running Android 6.0.1. Crash occurs when selecting "Camera" from the attachment button in the message composer. The first time I press the attachment "+" button it asks for permission and I grant permission then nothing happens so I press the "+" button again and choose "Camera" and get the crash.

![screen shot 2017-06-15 at 8 08 28 am](https://user-images.githubusercontent.com/2711642/27182847-4d46f788-51a2-11e7-81f0-b4e5b3dd33d8.png)

```
--------- beginning of crash
06-15 08:04:18.032 14225-14225/com.entrision.rentalgeek_chat E/AndroidRuntime: FATAL EXCEPTION: main
                                                                               Process: com.entrision.rentalgeek_chat, PID: 14225
                                                                               java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.res.XmlResourceParser android.content.pm.ProviderInfo.loadXmlMetaData(android.content.pm.PackageManager, java.lang.String)' on a null object reference
                                                                                   at android.support.v4.content.FileProvider.parsePathStrategy(FileProvider.java:583)
                                                                                   at android.support.v4.content.FileProvider.getPathStrategy(FileProvider.java:557)
                                                                                   at android.support.v4.content.FileProvider.getUriForFile(FileProvider.java:399)
                                                                                   at com.layer.atlas.messagetypes.threepartimage.CameraSender.startCameraIntent(CameraSender.java:69)
                                                                                   at com.layer.atlas.messagetypes.threepartimage.CameraSender.requestSend(CameraSender.java:87)
                                                                                   at com.layer.atlas.AtlasMessageComposer$4.onClick(AtlasMessageComposer.java:319)
                                                                                   at android.view.View.performClick(View.java:5198)
                                                                                   at android.view.View$PerformClick.run(View.java:21147)
                                                                                   at android.os.Handler.handleCallback(Handler.java:739)
                                                                                   at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                   at android.os.Looper.loop(Looper.java:148)
                                                                                   at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                                   at java.lang.reflect.Method.invoke(Native Method)
                                                                                   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

Here is my manifest:
```
<?xml version="1.0" encoding="utf-8"?>
<manifest
    package="..."
    xmlns:android="http://schemas.android.com/apk/res/android">

    <!-- Atlas GallerySender -->
    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE"/>
    <!-- Atlas CameraSender -->
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>
    <!-- Layer SDK -->
    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE"/>
    <uses-permission android:name="android.permission.INTERNET"/>
    <uses-permission android:name="android.permission.GET_ACCOUNTS" android:maxSdkVersion="18"/>
    <uses-permission android:name="android.permission.GET_TASKS" android:maxSdkVersion="20"/>

    <application
        android:allowBackup="true"
        android:icon="@mipmap/launcher_icon"
        android:name=".App"
        android:label="@string/app_name"
        android:supportsRtl="true"
        android:theme="@style/AppTheme">

        <activity
            android:name=".sign_in.SignInActivity"
            android:screenOrientation="portrait">
            <intent-filter>
                <action android:name="android.intent.action.MAIN"/>
                <category android:name="android.intent.category.LAUNCHER"/>
            </intent-filter>
        </activity>

        <activity
            android:name=".screens.property_list.PropertyListActivity"
            android:label="@string/properties"
            android:screenOrientation="portrait"/>

        <activity
            android:name=".screens.tenant_list.TenantListActivity"
            android:screenOrientation="portrait"/>

        <activity
            android:name=".screens.conversation.ConversationActivity"
            android:screenOrientation="portrait"/>

    </application>

</manifest>
```

**Comment by rajohns08** [comment]
Nevermind, I needed to add the FileProvider like that Atlas messenger sample app did:

```
<!-- Provider: FileProvider for CameraSender -->
        <provider
            android:name="android.support.v4.content.FileProvider"
            android:authorities="${applicationId}.file_provider"
            android:exported="false"
            android:grantUriPermissions="true">
            <meta-data
                android:name="android.support.FILE_PROVIDER_PATHS"
                android:resource="@xml/provider_paths"/>
        </provider>
```

**Comment by thecombatwombat** [comment]
@rajohns08 Yeah that's the solution right there. 

For future reference, we try and document some of this stuff in the docs folder. The camera sender details are here:

https://github.com/layerhq/Atlas-Android/blob/master/docs/CameraSender.md

**Comment by rajohns08** [comment]
Yeah sorry, I discovered the docs folder after I had the issue. I noticed even after adding everything the docs mention, after taking a photo and choosing it to send, it isn't showing up in the chat recycler view.
