### ISSUE TITLE
TransportException: NullPointerException: Attempt to invoke virtual method 'int com.layer.transport.lsdkc.b.ordinal()' on a null object reference

### ISSUE THREAD

**Issue by rohitramkumar308** [layerhq/Atlas-Android#217]
I get the following error when opening an existing conversation but it is too random. Does not happend everytime. What is int `com.layer.transport.lsdkc.b.ordinal()` ? 
```
                                               E/LayerSDK: k : TransportException: 
                                                                          java.lang.NullPointerException: Attempt to invoke virtual method 'int com.layer.transport.lsdkc.b.ordinal()' on a null object reference
                                                                              at com.layer.transport.lsdkc.f.a(ResponseType.java:29)
                                                                              at com.layer.transport.lsdkc.k.a(Transport.java:1385)
                                                                              at com.layer.transport.lsdkc.k.a(Transport.java:60)
                                                                              at com.layer.transport.lsdkc.k$f.a(Transport.java:400)
                                                                              at com.layer.transport.lsdkc.k.a(Transport.java:663)
                                                                              at com.layer.sdk.lsdka.lsdki.lsdkc.lsdka.f.a(GetPresenceTask.java:27)
                                                                              at com.layer.sdk.lsdka.lsdki.lsdkc.lsdka.f.a(GetPresenceTask.java:9)
                                                                              at com.layer.lsdka.lsdkc.d.run(Task.java:172)
                                                                              at com.layer.lsdka.lsdkc.a.run(DependentTask.java:171)
                                                                              at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
                                                                              at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
                                                                              at java.lang.Thread.run(Thread.java:761)
                                               E/LayerSDK: c : onTaskMasterStateChange returned with errors
                                               E/LayerSDK: c : Error in TaskMaster
                                                                          com.layer.lsdka.lsdkc.e: Uncaught Task exception
                                                                              at com.layer.lsdka.lsdkc.d.run(Task.java:176)
                                                                              at com.layer.lsdka.lsdkc.a.run(DependentTask.java:171)
                                                                              at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
                                                                              at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
                                                                              at java.lang.Thread.run(Thread.java:761)
                                                                           Caused by: com.layer.transport.lsdkc.m: Attempt to invoke virtual method 'int com.layer.transport.lsdkc.b.ordinal()' on a null object reference
                                                                              at com.layer.transport.lsdkc.k.a(Transport.java:1428)
                                                                              at com.layer.transport.lsdkc.k.a(Transport.java:60)
                                                                              at com.layer.transport.lsdkc.k$f.a(Transport.java:400)
                                                                              at com.layer.transport.lsdkc.k.a(Transport.java:663)
                                                                              at com.layer.sdk.lsdka.lsdki.lsdkc.lsdka.f.a(GetPresenceTask.java:27)
                                                                              at com.layer.sdk.lsdka.lsdki.lsdkc.lsdka.f.a(GetPresenceTask.java:9)
                                                                              at com.layer.lsdka.lsdkc.d.run(Task.java:172)
                                                                              at com.layer.lsdka.lsdkc.a.run(DependentTask.java:171) 
                                                                              at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133) 
                                                                              at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607) 
                                                                              at java.lang.Thread.run(Thread.java:761) 
                                                                           Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'int com.layer.transport.lsdkc.b.ordinal()' on a null object reference
                                                                              at com.layer.transport.lsdkc.f.a(ResponseType.java:29)
                                                                              at com.layer.transport.lsdkc.k.a(Transport.java:1385)
                                                                              at com.layer.transport.lsdkc.k.a(Transport.java:60) 
                                                                              at com.layer.transport.lsdkc.k$f.a(Transport.java:400) 
                                                                              at com.layer.transport.lsdkc.k.a(Transport.java:663) 
                                                                              at com.layer.sdk.lsdka.lsdki.lsdkc.lsdka.f.a(GetPresenceTask.java:27) 
                                                                              at com.layer.sdk.lsdka.lsdki.lsdkc.lsdka.f.a(GetPresenceTask.java:9) 
                                                                              at com.layer.lsdka.lsdkc.d.run(Task.java:172) 
                                                                              at com.layer.lsdka.lsdkc.a.run(DependentTask.java:171) 
                                                                              at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133) 
                                                                              at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607) 
                                                                              at java.lang.Thread.run(Thread.java:761) 
                                               E/LayerSDK: a : Exception during sync
                                                                          com.layer.sdk.exceptions.LayerException: UNKNOWN (1000) - Uncaught Task exception
                                                                              at com.layer.sdk.lsdka.lsdki.a$d.a(SyncRecon.java:616)
                                                                              at com.layer.sdk.lsdka.lsdki.a$d.run(SyncRecon.java:794)
                                                                              at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
                                                                              at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
                                                                              at java.lang.Thread.run(Thread.java:761)
                                                                           Caused by: com.layer.transport.lsdkc.m: Attempt to invoke virtual method 'int com.layer.transport.lsdkc.b.ordinal()' on a null object reference
                                                                              at com.layer.transport.lsdkc.k.a(Transport.java:1428)
                                                                              at com.layer.transport.lsdkc.k.a(Transport.java:60)
                                                                              at com.layer.transport.lsdkc.k$f.a(Transport.java:400)
                                                                              at com.layer.transport.lsdkc.k.a(Transport.java:663)
                                                                              at com.layer.sdk.lsdka.lsdki.lsdkc.lsdka.f.a(GetPresenceTask.java:27)
                                                                              at com.layer.sdk.lsdka.lsdki.lsdkc.lsdka.f.a(GetPresenceTask.java:9)
                                                                              at com.layer.lsdka.lsdkc.d.run(Task.java:172)
                                                                              at com.layer.lsdka.lsdkc.a.run(DependentTask.java:171)
                                                                              at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133) 
                                                                              at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607) 
                                                                              at java.lang.Thread.run(Thread.java:761) 
                                                                           Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'int com.layer.transport.lsdkc.b.ordinal()' on a null object reference
                                                                              at com.layer.transport.lsdkc.f.a(ResponseType.java:29)
                                                                              at com.layer.transport.lsdkc.k.a(Transport.java:1385)
```

**Comment by csbrandt** [comment]
A fix for this issue is released in version [0.23.16](https://github.com/layerhq/releases-android/blob/master/CHANGELOG.md#02316) of the Android SDK, also check the [Android SDK Change Log](https://github.com/layerhq/releases-android/blob/master/CHANGELOG.md) for additional updates and enhancements.

Thanks,
Chris

**Comment by rohitramkumar308** [comment]
Now I get this issue with 0.23.16:

```
                                                    E/LayerSDK: k : TransportException: 
                                                                          com.layer.transport.lsdkc.m: Response type: RETRYABLE_RIGHT_NOW, error code: TRANSPORT_PUSH_NOT_ESTABLISHED, status code (200): OK, message: connection_not_established: connection_not_established
                                                                              at com.layer.transport.lsdkc.k.a(Transport.java:1408)
                                                                              at com.layer.transport.lsdkc.k.a(Transport.java:60)
                                                                              at com.layer.transport.lsdkc.k$f.a(Transport.java:400)
                                                                              at com.layer.transport.lsdkc.k.a(Transport.java:681)
                                                                              at com.layer.sdk.internal.lsdki.lsdkc.lsdka.f.a(GetPresenceTask.java:38)
                                                                              at com.layer.sdk.internal.lsdki.lsdkc.lsdka.f.a(GetPresenceTask.java:14)
                                                                              at com.layer.lsdka.lsdkc.d.run(Task.java:172)
                                                                              at com.layer.lsdka.lsdkc.a.run(DependentTask.java:171)
                                                                              at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
                                                                              at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
                                                                              at java.lang.Thread.run(Thread.java:761)
                                                    E/LayerSDK: f : Error in GetPresenceTask
                                                                          com.layer.transport.lsdkc.m: Response type: RETRYABLE_RIGHT_NOW, error code: TRANSPORT_PUSH_NOT_ESTABLISHED, status code (200): OK, message: connection_not_established: connection_not_established
                                                                              at com.layer.transport.lsdkc.k.a(Transport.java:1408)
                                                                              at com.layer.transport.lsdkc.k.a(Transport.java:60)
                                                                              at com.layer.transport.lsdkc.k$f.a(Transport.java:400)
                                                                              at com.layer.transport.lsdkc.k.a(Transport.java:681)
                                                                              at com.layer.sdk.internal.lsdki.lsdkc.lsdka.f.a(GetPresenceTask.java:38)
                                                                              at com.layer.sdk.internal.lsdki.lsdkc.lsdka.f.a(GetPresenceTask.java:14)
                                                                              at com.layer.lsdka.lsdkc.d.run(Task.java:172)
                                                                              at com.layer.lsdka.lsdkc.a.run(DependentTask.java:171)
                                                                              at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
                                                                              at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
                                                                              at java.lang.Thread.run(Thread.java:761)
```

**Comment by csbrandt** [comment]
For technical assistance please reach out to us via [support.layer.com](https://support.layer.com/).

Thanks,
Chris
