### ISSUE TITLE
CameraSender not checking for Manifest.permission.CAMERA

### ISSUE THREAD

**Issue by mdumrauf** [layerhq/Atlas-Android#224]
`CameraSender.java#L84`
```java
    @Override
    public boolean requestSend() {
        Activity activity = mActivity.get();
        if (activity == null) return false;

        if (Log.isLoggable(Log.VERBOSE)) Log.v("Checking permissions");

        if (!hasPermissions(activity, PERMISSION_READ, PERMISSION_WRITE)) {
            requestPermissions(activity, PERMISSION_REQUEST_CODE, PERMISSION_READ, PERMISSION_WRITE);
        } else {
            startCameraIntent(activity);
        }

        return true;
    }

```

Where:

```java
private static final String PERMISSION_READ = (Build.VERSION.SDK_INT >= Build.VERSION_CODES.JELLY_BEAN) ? Manifest.permission.READ_EXTERNAL_STORAGE : null;
private static final String PERMISSION_WRITE = (Build.VERSION.SDK_INT >= Build.VERSION_CODES.JELLY_BEAN) ? Manifest.permission.WRITE_EXTERNAL_STORAGE : null;
```

If the user happens to remove CAMERA permission then the `AtlasMessageComposer` crashes:

```
Fatal Exception: java.lang.RuntimeException: Failure delivering result ResultInfo{who=@android:requestPermissions:, request=110, result=-1, data=Intent { act=android.content.pm.action.REQUEST_PERMISSIONS (has extras) }} to activity {com.foo.bar/com.foo.bar.activity.layer.MessagesListActivity}: java.lang.SecurityException: Permission Denial: starting Intent { act=android.media.action.IMAGE_CAPTURE flg=0x3 cmp=com.motorola.cameraone/com.motorola.camera.Camera clip={text/uri-list U:content://com.foo.bar.file_provider/external_files/Pictures/cameraOutput1499548875553.jpg} (has extras) } from ProcessRecord{5605fc1 12552:com.foo.bar/u0a144} (pid=12552, uid=10144) with revoked permission android.permission.CAMERA
       at android.app.ActivityThread.deliverResults(ActivityThread.java:4094)
       at android.app.ActivityThread.handleSendResult(ActivityThread.java:4137)
       at android.app.ActivityThread.-wrap20(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1529)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6123)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:867)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:757)
Caused by java.lang.SecurityException: Permission Denial: starting Intent { act=android.media.action.IMAGE_CAPTURE flg=0x3 cmp=com.motorola.cameraone/com.motorola.camera.Camera clip={text/uri-list U:content://com.foo.bar.file_provider/external_files/Pictures/cameraOutput1499548875553.jpg} (has extras) } from ProcessRecord{5605fc1 12552:com.foo.bar/u0a144} (pid=12552, uid=10144) with revoked permission android.permission.CAMERA
       at android.os.Parcel.readException(Parcel.java:1683)
       at android.os.Parcel.readException(Parcel.java:1636)
       at android.app.ActivityManagerProxy.startActivity(ActivityManagerNative.java:3159)
       at android.app.Instrumentation.execStartActivity(Instrumentation.java:1584)
       at android.app.Activity.startActivityForResult(Activity.java:4228)
       at android.support.v4.app.BaseFragmentActivityJB.startActivityForResult(BaseFragmentActivityJB.java:50)
       at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:79)
       at android.app.Activity.startActivityForResult(Activity.java:4187)
       at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:859)
       at com.layer.atlas.messagetypes.threepartimage.CameraSender.startCameraIntent(CameraSender.java:74)
       at com.layer.atlas.messagetypes.threepartimage.CameraSender.onRequestPermissionsResult(CameraSender.java:106)
       at com.layer.atlas.AtlasMessageComposer.onRequestPermissionsResult(AtlasMessageComposer.java:259)
       at com.foo.bar.activity.layer.MessagesListActivity.onRequestPermissionsResult(MessagesListActivity.java:332)
       at android.app.Activity.dispatchRequestPermissionsResult(Activity.java:7083)
       at android.app.Activity.dispatchActivityResult(Activity.java:6935)
       at android.app.ActivityThread.deliverResults(ActivityThread.java:4090)
       at android.app.ActivityThread.handleSendResult(ActivityThread.java:4137)
       at android.app.ActivityThread.-wrap20(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1529)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6123)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:867)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:757)
```

**Comment by victorpetrovski** [comment]
Any solutions to this ?

**Comment by andela-wakinsanmi** [comment]
This has been merged to the develop branch https://github.com/layerhq/Atlas-Android/pull/225/files It will be out with the next release.

Thanks

**Comment by antonverhoeven32** [comment]
@andela-wakinsanmi I am experiencing the same issue, what is the ETA of next release?
