### ISSUE TITLE
Persistence Closed Error when opening conversation

### ISSUE THREAD

**Issue by daverhost** [layerhq/Atlas-Android#237]
Our Android client is using Atlas/Layer for messaging.  When calling the following:
Conversation conversation = getLayerClient().getConversation(conversationId);
I am receiving these fatal crashes:
FATAL CRASH - com.layer.sdk.exceptions.LayerException: 

PERSISTENCE_CLOSED (-1006) - Cannot perform read operation while persistence is closed.
at com.layer.sdk.lsdka.lsdke.g.a(SyncPersistence.java:344)
at com.layer.sdk.lsdka.lsdke.g.d(SyncPersistence.java:1357)
at com.layer.sdk.lsdka.lsdkd.f.c(ChangeableCache.java:567)
at com.layer.sdk.lsdka.lsdkd.f.a(ChangeableCache.java:356)
at com.layer.sdk.lsdka.b.j(LayerSession.java:179)
at com.layer.sdk.lsdka.a.a(LayerClientImpl.java:963)
at com.layer.sdk.lsdka.a.a(LayerClientImpl.java:1095)
at com.layer.sdk.lsdka.lsdkk.lsdka.a.a(AuthManager.java:669)
at com.layer.sdk.lsdka.lsdkk.lsdka.a$1.b(AuthManager.java:496)
at com.layer.lsdka.lsdkc.c.run(RetryableTask.java:193)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
at java.lang.Thread.run(Thread.java:818)

The crash usually occurs under the following condition:
1) The user closes the app and then immediately restarts the app and opens the conversation.

I would appreciate any help determining why the Persistence closed crash occurs and how I avoid this crash.

Thank you,

David Hosetetler
Chime Android Lead

**Comment by csbrandt** [comment]
For technical assistance please reach out to us via [support.layer.com](https://support.layer.com/).
