### ISSUE TITLE
Crash when attempting to display message with gif image part

### ISSUE THREAD

**Issue by timusus** [layerhq/Atlas-Android#254]
**Device:** 
Nexus 6P, Android 8.0.0

**SDK Version:**
 0.4.13, 0.4.14

**Issue:**
It looks like a gif was uploaded as the image attachment for a message on the iOS app. When attempting to render this message via the `AtlasMessagesAdapter` in Android, the app crashes (stack trace at bottom).

I have supplied the following `Cell Factories` to the `AtlasMessagesRecyclerView`:
``` kotlin
messagesRecyclerView
    ...
    .addCellFactories(
           TextCellFactory(),
           ThreePartImageCellFactory(ChatManager.client, picasso),
           LocationCellFactory(picasso),
           SinglePartImageCellFactory(ChatManager.client, picasso))
```

`AtlasMessagesAdapter` attempts to return a type based on whichever `CellFactory` `isBindable()` for the current message. In this particular case, I would expect `ThreePartImageCellFactory` to be the correct candidate. The problem lies in the `ThreePartImageCellFactory.isType()` call.

The message's `PREVIEW` `Part` mimetype is `image/gif+preview`. 

`ThreePartImageCellFactory.isType()` looks like this:
```Java
public boolean isType(Message message) {
    List<MessagePart> parts = message.getMessageParts();
    return parts.size() == 3 &&
            parts.get(ThreePartImageUtils.PART_INDEX_FULL).getMimeType().startsWith("image/") &&
            parts.get(ThreePartImageUtils.PART_INDEX_PREVIEW).getMimeType().equals(ThreePartImageUtils.MIME_TYPE_PREVIEW) &&
            parts.get(ThreePartImageUtils.PART_INDEX_INFO).getMimeType().equals(ThreePartImageUtils.MIME_TYPE_INFO);
}
```
`isType()` will only return true if the `PREVIEW` `Part` mimetype equals `MIME_TYPE_PREVIEW`, which resolves to `image/jpeg+preview`. So the preview image must be a `jpeg`, `gif` is not supported.

Since no `CellFactories` return true for `isBindable()` in the `AtlasMessagesAdapter`, the adapter's `getItemViewType()` returns a value of `-1`. When `onCreateViewHolder()` is called, no `CellType` can be found for a `viewType` of `-1`. `cellType` is thus `null`, and `cellType.mMe` fails with an NPE.

It looks like the root of this problem is the preview part of an image probably should always be a jpeg, the `gif` mimetype should not have been included in the first place (so possibly a bug in the iOS SDK?).

**Recommendation**

1. I would recommend `getItemViewType()` throw an `Exception` rather than return an invalid `ViewType` of `-1` (crash early). 

2. It would be good to see `ThreePartImageCellFactory` support all possible preview mimetypes that can be thrown at it. If a mime type (such as gif) is not supported, perhaps the `ThreePartImageCellFactory` can render a placeholder instead? 

**Steps to reproduce:**
Just guessing here:
1. Using layer sdk on an iOS device, submit a message with a gif image
2. Open message in `AtlasMessagesRecyclerView` on Android device
3. Observe crash

**Stacktrace:**
```
java.lang.NullPointerException: Attempt to read from field 'boolean com.layer.atlas.adapters.AtlasMessagesAdapter$CellType.mMe' on a null object reference
  at com.layer.atlas.adapters.AtlasMessagesAdapter.onCreateViewHolder(AtlasMessagesAdapter.java:298)
  at com.layer.atlas.adapters.AtlasMessagesAdapter.onCreateViewHolder(AtlasMessagesAdapter.java:63)
  at android.support.v7.widget.RecyclerView$Adapter.createViewHolder(RecyclerView.java:6367)
  at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5555)
  at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5440)
  at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5436)
  at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2224)
  at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1551)
  at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1511)
  at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:570)
  at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3583)
  at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3312)
  at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3844)
```

**Temporary Workaround:**
As a temporary workaround, to prevent crashing, just check whether the preview mimetype starts with `image/` and contains `+preview`, in `ThreePartImageCellFactory`:

```Java
    public boolean isType(Message message) {
        List<MessagePart> parts = message.getMessageParts();
        return parts.size() == 3 &&
                parts.get(ThreePartImageUtils.PART_INDEX_FULL).getMimeType().startsWith("image/") &&
                parts.get(ThreePartImageUtils.PART_INDEX_PREVIEW).getMimeType().startsWith("image/") && 
                parts.get(ThreePartImageUtils.PART_INDEX_PREVIEW).getMimeType().contains("+preview") &&
                parts.get(ThreePartImageUtils.PART_INDEX_INFO).getMimeType().equals(ThreePartImageUtils.MIME_TYPE_INFO);
    }
```

**Comment by thecombatwombat** [comment]
@timusus Thanks for the detailed ticket!

I'm going to file a work item for us to address this issue. I don't yet have a timeline for when we'll have a fix out. 

In the meanwhile, a fix you could easily implement is to subclass `ThreePartImageCellFactory` and override the `isType` with the contents of above workaround.

**Comment by timusus** [comment]
No worries.

I've since realised that adding the `GenericCellFactory` is probably another simple workaround for this issue.

**Comment by timusus** [comment]
@thecombatwombat is this _resolved_ due to some internal change, or because of the workaround above?

**Comment by thecombatwombat** [comment]
@timusus a bit of both. I've marked it for fixing in the future, since we have a workaround for you now. 

Won't be a super quick fix since I'd like to make sure the types are coordinated across platforms, so that something like this does not happen again.

**Comment by timusus** [comment]
OK, would you consider reopening this ticket until the issue is resolved? It's a bit unconventional to me to have 'closed' issues which are in-progress or pending a fix. It leads to the expectation that the a fix is about to become available in the next release, which is not the case here.
