### ISSUE TITLE
MESSAGE_ALREADY_SENT (1007) - Cannot send an already-sent Message.

### ISSUE THREAD

**Issue by SnowGhost21** [layerhq/Atlas-Android#291]
Hi,
I'm trying create a mass sender of message because the Android sdk doesn't support channels and when I try send a random message to a random group i received the follow stacktrace:

`Cannot send an already-sent Message.
                                                                                   com.layer.sdk.exceptions.LayerException: MESSAGE_ALREADY_SENT (1007) - Cannot send an already-sent Message.
                                                                                       at com.layer.sdk.lsdka.lsdkd.lsdka.c$6.a(ConversationImpl.java:535)
                                                                                       at com.layer.sdk.lsdka.lsdkk.f.a(ExecutorValidator.java:71)
                                                                                       at com.layer.sdk.lsdka.a.a(LayerClientImpl.java:1358)
                                                                                       at com.layer.sdk.lsdka.lsdkd.lsdka.c.send(ConversationImpl.java:530)
                                                                                       at com.layer.sdk.lsdka.lsdkd.lsdka.c.send(ConversationImpl.java:521)
... `

**Comment by thecombatwombat** [comment]
For technical assistance please reach out to us via support.layer.com
