### ISSUE TITLE
com.layer.sdk.services.GcmBroadcastReceiver: java.lang.NullPointerException

### ISSUE THREAD

**Issue by akak19193** [layerhq/Atlas-Android#59]
Fatal Exception: java.lang.RuntimeException: Unable to start receiver com.layer.sdk.services.GcmBroadcastReceiver: java.lang.NullPointerException
       at android.app.ActivityThread.handleReceiver(ActivityThread.java:2274)
       at android.app.ActivityThread.access$1500(ActivityThread.java:131)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1272)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:137)
       at android.app.ActivityThread.main(ActivityThread.java:4791)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:511)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
       at dalvik.system.NativeStart.main(NativeStart.java)
Caused by java.lang.NullPointerException
       at com.layer.sdk.services.GcmBroadcastReceiver.onReceive(GcmBroadcastReceiver.java:20)
       at android.app.ActivityThread.handleReceiver(ActivityThread.java:2267)
       at android.app.ActivityThread.access$1500(ActivityThread.java:131)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1272)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:137)
       at android.app.ActivityThread.main(ActivityThread.java:4791)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:511)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
       at dalvik.system.NativeStart.main(NativeStart.java)

**Comment by andela-wakinsanmi** [comment]
Hello @akak19193 

Please kindly check this to troubleshoot this https://docs.layer.com/sdk/android/push#troubleshooting-and-integration-checklist

**Comment by sriamar** [comment]
Hi @akak19193 

Hope the docs & checklist help you resolve the issue. If you still have problems with this, please contact Layer Support via https://support.layer.com/hc/en-us . 

Thanks,
Amar
