### ISSUE TITLE
getting   SSL handshake aborted

### ISSUE THREAD

**Issue by vikram-kadam** [layerhq/Atlas-Android#61]
Retrying connection in 29333 ms due to: SSL handshake aborted: ssl=0x60296340: I/O error during system call, Connection reset by peer
            javax.net.ssl.SSLException: SSL handshake aborted: ssl=0x60296340: I/O error during system call, Connection reset by peer
                at com.android.org.conscrypt.NativeCrypto.SSL_do_handshake(Native Method)
                at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:406)
                at com.lsdka.lsdka.lsdka.lsdka.q.a(SocketConnector.java:103)

**Comment by sriamar** [comment]
Hello @vikram-kadam ,

This was an old issue in Layer Android SDK. This should be fixed now in the latest versions of SDK. If you still have issues, please collect logs and reach out to Layer Support using instructions provided here https://docs.layer.com/sdk/android/support#logging-on-android

Thanks,
Amar
