### ISSUE TITLE
content:// URI crashes at ThreePartImageUtils.newThreePartImageMessage 

### ISSUE THREAD

**Issue by derekcsm** [layerhq/Atlas-Android#95]
Heyo! I found a bug 🐛 

An exception will occur when a [ContentUri](https://developer.android.com/reference/android/content/ContentUris.html) is passed into `ThreePartImageUtils.newThreePartImageMessage`.

Below is the full log, I hope this helps!

```
Fatal Exception: java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=10, result=-1, data=Intent { dat=content://com.google.android.apps.photos.contentprovider/1/1/mediakey:/AF1QipOAj-CrbFeuqSDgkDhrqOb3dFKLzyNuQbr8afof/ORIGINAL/NONE/412820524 flg=0x1 clip={text/uri-list U:content://com.google.android.apps.photos.contentprovider/1/1/mediakey%3A%2FAF1QipOAj-CrbFeuqSDgkDhrqOb3dFKLzyNuQbr8afof/ORIGINAL/NONE/412820524} }} to activity {com.airy.messenger/com.airy.messenger.channel.ChannelActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'char[] java.lang.String.toCharArray()' on a null object reference
       at android.app.ActivityThread.deliverResults(ActivityThread.java:3699)
       at android.app.ActivityThread.handleSendResult(ActivityThread.java:3742)
       at android.app.ActivityThread.-wrap16(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1393)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:5417)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'char[] java.lang.String.toCharArray()' on a null object reference
       at java.io.File.fixSlashes(File.java:183)
       at java.io.File.<init>(File.java:130)
       at com.layer.atlas.messagetypes.threepartimage.ThreePartImageUtils.newThreePartImageMessage(ThreePartImageUtils.java:56)
       at com.airy.messenger.message_composer.sender.GallerySender.onActivityResult(GallerySender.java:119)
       at com.airy.messenger.message_composer.MessageComposer.onActivityResult(MessageComposer.java:245)
       at com.airy.messenger.channel.ChannelActivity.onActivityResult(ChannelActivity.java:165)
       at android.app.Activity.dispatchActivityResult(Activity.java:6428)
       at android.app.ActivityThread.deliverResults(ActivityThread.java:3695)
       at android.app.ActivityThread.handleSendResult(ActivityThread.java:3742)
       at android.app.ActivityThread.-wrap16(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1393)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:5417)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

**Comment by derekcsm** [comment]
So here's a fix that I like which works well

```
  public static Message newThreePartImageMessage(Context context, LayerClient layerClient, Uri imageUri) throws IOException {
    InputStream fileStream = context.getContentResolver().openInputStream(imageUri);
    File imageFile = stream2file(fileStream);
    return newThreePartImageMessage(context, layerClient, imageFile);
  }

  private static final String PREFIX = "stream2file";
  private static final String SUFFIX = ".tmp";

  private static File stream2file(InputStream in) throws IOException {
    final File tempFile = File.createTempFile(PREFIX, SUFFIX);
    tempFile.deleteOnExit();

    FileOutputStream out = new FileOutputStream(tempFile);
    IOUtils.copy(in, out);

    return tempFile;
  }
```

I'm using the commons IO library for IOUtils (`compile "commons-io:commons-io:2.4"`)

**Comment by thecombatwombat** [comment]
@derekcsm sorry it took us some time to get to this!
 #143 has been created to address this, so it should ship with the next version of Atlas
